#!/bin/bash
# PreToolUse hook: Block edits to generated files.
# docs/data/briefing.json is regenerated by the scraper — manual edits are lost.

input=$(cat)
file_path=$(echo "$input" | jq -r '.tool_input.file_path // .tool_input.path // ""')

if [[ "$file_path" == *"docs/data/briefing.json"* ]]; then
  cat <<'EOF'
{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"docs/data/briefing.json is generated by the scraper. Edit source modules in scraper/sources/ instead, then run: python -m scraper.main"}}
EOF
  exit 0
fi

echo '{}'
exit 0
